name: client
description: Shanbe client app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  get_it: ^7.2.0
  flutter_svg: ^1.1.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  webview_flutter: ^3.0.0
  enum_to_string: ^2.0.1
  timeago: ^3.3.0
  path_provider: ^2.0.11
  open_filex: ^4.3.1
  file_picker: ^5.2.3
  logging: ^1.0.2
  web_socket_channel: ^2.2.0
  url_launcher: ^6.0.20
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.9
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  firebase_dynamic_links: ^5.0.11
  cloud_firestore: ^4.3.1
  connectivity_plus: ^2.3.7
  package_info_plus: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^11.0.0
  flutter_keyboard_visibility: ^5.3.0
  flutter_emoji: ^2.4.0
  uuid: ^3.0.7
  flutter_sticky_header: ^0.6.4
  scrollable_positioned_list: ^0.3.4
  smooth_page_indicator: ^1.0.0+2
  share_plus: ^4.0.4
  permission_handler: ^10.0.1
  timeline_tile: ^2.0.0
  jdenticon_dart: ^2.0.0
  app_settings: ^4.1.5
  uni_links: ^0.5.1
  flutter_reorderable_list: ^1.2.0
  flutter_dotenv: ^5.0.2
  implicitly_animated_reorderable_list: ^0.4.2
  cached_network_image: ^3.2.2
  lottie: ^1.2.2
  local_auth: ^2.0.0
  speech_to_text: ^5.4.3
  assets_audio_player: ^3.0.4+1
  shamsi_date: ^1.0.1
  flutter_platform_widgets: ^2.0.0
  crypto: ^3.0.2
  salomon_bottom_bar: ^3.3.1
  flutter_signin_button: ^2.0.0
  rrule: ^0.2.10
  modal_bottom_sheet: ^2.1.2
  device_preview: ^1.1.0
  macos_ui: ^1.7.5
  popover: ^0.2.7
  window_manager: ^0.2.8
  loading_animation_widget: ^1.2.0+4
  form_validator: ^2.1.1
  fluttertoast: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/sounds/
    - assets/files/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/noto-sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto-sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto-sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto-sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto-sans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/noto-sans/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/noto-sans/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/noto-sans/NotoSans-Italic.ttf
          weight: 400
          style: italic
    - family: Graphik
      fonts:
        - asset: assets/fonts/graphik/Graphik-Bold.otf
          weight: 700
        - asset: assets/fonts/graphik/Graphik-Demi-Bold.otf
          weight: 600
        - asset: assets/fonts/graphik/Graphik-Medium.otf
          weight: 500
        - asset: assets/fonts/graphik/Graphik-Regular.otf
          weight: 400
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransans/IranSansX-Bold.ttf
          weight: 700
        - asset: assets/fonts/iransans/IranSansX-Demi-Bold.ttf
          weight: 600
        - asset: assets/fonts/iransans/IranSansX-Medium.ttf
          weight: 500
        - asset: assets/fonts/iransans/IranSansX-Regular.ttf
          weight: 400
    - family: Shanbe
      fonts:
        - asset: assets/fonts/icons/Shanbe.ttf
