// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKO-SlDyHWTa01ruzDlNmK9v2YMnBZP_0',
    appId: '1:308286860901:android:2392d47afead2fcb14208c',
    messagingSenderId: '308286860901',
    projectId: 'shanbe-cdebc',
    storageBucket: 'shanbe-cdebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUKxxue5cLlfKTzf_L6cD--e4JPo75x0',
    appId: '1:308286860901:ios:0b70b9f8b9da502f14208c',
    messagingSenderId: '308286860901',
    projectId: 'shanbe-cdebc',
    storageBucket: 'shanbe-cdebc.appspot.com',
    iosClientId: '308286860901-tr0j3tq8g3jqunir15o116t39889k0fp.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUKxxue5cLlfKTzf_L6cD--e4JPo75x0',
    appId: '1:308286860901:ios:0b70b9f8b9da502f14208c',
    messagingSenderId: '308286860901',
    projectId: 'shanbe-cdebc',
    storageBucket: 'shanbe-cdebc.appspot.com',
    iosClientId: '308286860901-tr0j3tq8g3jqunir15o116t39889k0fp.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );
}
