// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDeSlcZZxlgV0waxanxOJzoJEowerDa-o',
    appId: '1:328657175996:android:3d290fb8fd15db44c917b9',
    messagingSenderId: '328657175996',
    projectId: 'shanbe-2f899',
    storageBucket: 'shanbe-2f899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW2PgXhuG6hubL0NuDw9NIFwVTarVQOQ8',
    appId: '1:328657175996:ios:0e2484798d827252c917b9',
    messagingSenderId: '328657175996',
    projectId: 'shanbe-2f899',
    storageBucket: 'shanbe-2f899.appspot.com',
    iosClientId: '328657175996-5s8rj1t3p3fv26h4m7m1fcv0ke7jsj99.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW2PgXhuG6hubL0NuDw9NIFwVTarVQOQ8',
    appId: '1:328657175996:ios:0e2484798d827252c917b9',
    messagingSenderId: '328657175996',
    projectId: 'shanbe-2f899',
    storageBucket: 'shanbe-2f899.appspot.com',
    iosClientId: '328657175996-5s8rj1t3p3fv26h4m7m1fcv0ke7jsj99.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );
}
