// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl85ebYA7YOpP04hFc_cUOD2_ajQrPv7k',
    appId: '1:641408115307:android:4ac02e0312f5497b6bc72e',
    messagingSenderId: '641408115307',
    projectId: 'shanbe-app',
    storageBucket: 'shanbe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoyFpq6eVkith56wwjLHVPbpe8fO5UMzQ',
    appId: '1:641408115307:ios:4295cbf99558ce276bc72e',
    messagingSenderId: '641408115307',
    projectId: 'shanbe-app',
    storageBucket: 'shanbe-app.appspot.com',
    iosClientId: '641408115307-ou6obst0o6qc5knt3pqfuqjnbugobfsv.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoyFpq6eVkith56wwjLHVPbpe8fO5UMzQ',
    appId: '1:641408115307:ios:4295cbf99558ce276bc72e',
    messagingSenderId: '641408115307',
    projectId: 'shanbe-app',
    storageBucket: 'shanbe-app.appspot.com',
    iosClientId: '641408115307-ou6obst0o6qc5knt3pqfuqjnbugobfsv.apps.googleusercontent.com',
    iosBundleId: 'app.shanbe.client',
  );
}
