/// Flutter icons Shanbe
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shanbe
///      fonts:
///       - asset: fonts/Shanbe.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Shanbe {
  Shanbe._();

  static const _kFontFam = 'Shanbe';
  static const String? _kFontPkg = null;

  static const IconData list_add =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble_chart =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile =
      IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye =
      IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_h =
      IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist =
      IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist =
      IconData(0xf31c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
