// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'package:client/types/enums.dart';
import 'package:client/types/hex_color.dart';
import 'package:flutter/material.dart';

class Constants {
  Constants._();

  static const Locale DEFAULT_LOCALE = Locale('en');
  static const ThemeType DEFAULT_THEME = ThemeType.system;
  static const CalendarType DEFAULT_CALENDAR = CalendarType.gregorian;
  static final List<StaticTaskListType> DEFAULT_STATIC_TASK_LISTS = [
    StaticTaskListType.today,
    StaticTaskListType.tomorrow,
    StaticTaskListType.done,
    StaticTaskListType.trash,
  ];
  static const StartOfTheWeekType DEFAULT_START_OF_THE_WEEK =
      StartOfTheWeekType.monday;
  static const String INDEX_PROJECT_NAME = 'shanbe_todo_index_project';
  static const String ACCESS_TOKEN_PREFS = 'access_token';
  static const String REFRESH_TOKEN_PREFS = 'refresh_token';
  static const String SHOW_NOTIFICATIONS_PREFS = 'SHOW_NOTIFICATIONS_PREFS';
  static const String FIRST_VISIT_PREFS = 'first_visit';
  static const String USER_LOCALE_PREFS = 'user_locale';
  static const String USER_CALENDAR_PREFS = 'user_calendar';
  static const String USER_THEME_PREFS = 'user_theme';
  static const String USER_DAILY_NOTIFICATION_TIME_PREFS =
      'user_daily_notification_time';
  static const String ENABLED_APP_AUTH_PREFS = 'enabled_app_auth';
  static const String USER_DAILY_NOTIFICATION_SENT_TODAY_PREFS =
      'user_daily_notification_sent_today';
  static const String USER_QUICK_ADD_PREFS = 'user_quick_add';
  static const String SOUND_ON_COMPLETE_PREFS = 'sound_on_complete';
  static const String SOUND_ON_CREATE_PREFS = 'sound_on_create';

  static final Color PRIMARY_COLOR = Colors.blue.shade300;
  static final Color PRIMARY_COLOR_DARK = Colors.blue.shade500;
  static final Color PRIMARY_COLOR_LIGHT = Colors.blue.shade200;
  static final Color SECONDARY_COLOR = Colors.pink.shade300;
  static final Color SECONDARY_COLOR_DARK = Colors.pink.shade400;
  static final Color SECONDARY_COLOR_LIGHT = Colors.pink.shade200;
  static const Color ERROR_COLOR = Color.fromRGBO(237, 46, 126, 1);
  static const Color ERROR_COLOR_DARK = Color.fromRGBO(195, 0, 82, 1);
  static const Color ERROR_COLOR_LIGHT = Color.fromRGBO(255, 242, 247, 1);
  static const Color SUCCESS_COLOR = Color.fromRGBO(0, 186, 136, 1);
  static const Color SUCCESS_COLOR_DARK = Color.fromRGBO(0, 186, 136, 1);
  static const Color WARNING_COLOR = Color.fromRGBO(244, 183, 64, 1);
  static const Color WARNING_COLOR_LIGHT = Color.fromRGBO(255, 240, 212, 1);
  static const Color WARNING_COLOR_DARK = Color.fromRGBO(162, 107, 0, 1);
  static const Color TEXT_BLACK_COLOR = Color.fromRGBO(20, 20, 43, 1);
  static const Color TEXT_BLACK_COLOR_DARK = Color.fromRGBO(235, 235, 212, 1.0);
  static const Color TEXT_BODY_COLOR = Color.fromRGBO(78, 75, 102, 1.0);
  static const Color TEXT_BODY_COLOR_DARK = Color.fromRGBO(203, 203, 203, 1);
  static const Color TEXT_LABEL_COLOR = Color.fromRGBO(110, 113, 145, 1);
  static const Color TEXT_LABEL_COLOR_DARK = Color.fromRGBO(145, 142, 110, 1.0);
  static const Color PLACEHOLDER_COLOR = Color.fromRGBO(160, 163, 189, 1);
  static const Color PLACEHOLDER_COLOR_DARK = Color.fromRGBO(95, 92, 66, 1.0);
  static const Color LINE_COLOR = Color.fromRGBO(214, 216, 231, 1);
  static const Color LINE_COLOR_DARK = Color.fromRGBO(41, 39, 24, 1.0);
  static Color GRAY_COLOR = HexColor.fromHex('#505050');
  static Color GRAY_COLOR_DARK = HexColor.fromHex('#383838');
  static Color GRAY_LIGHTER_COLOR = HexColor.fromHex('#979797');
  static Color GRAY_LIGHTER_COLOR_DARK = HexColor.fromHex('#7a7a7a');
  static Color BARRIER_COLOR = const Color.fromRGBO(20, 20, 43, .4);
  static const Color BACKGROUND_COLOR_MODAL_SHEET = Colors.white;
  static const Color BACKGROUND_COLOR_MODAL_SHEET_DARK =
      Color.fromRGBO(33, 34, 38, 1.0);
  static const Color BACKGROUND_COLOR = Color.fromRGBO(239, 243, 247, 1.0);
  static const Color BACKGROUND_COLOR_DARK = Color.fromRGBO(16, 12, 8, 1.0);
  static const Color INPUT_BACKGROUND_COLOR = Color.fromRGBO(239, 240, 246, 1);
  static const Color INPUT_BACKGROUND_COLOR_DARK =
      Color.fromRGBO(16, 15, 9, 1.0);

  static const double ICON_SMALL_SIZE = 18;
  static const double ICON_MEDIUM_SIZE = 24;
  static const double ICON_LARGE_SIZE = 32;
  static const double ICON_X_LARGE_SIZE = 40;
  static const double CAPTION_FONT_SIZE = 12;
  static const double S2_FONT_SIZE = 14;
  static const double S1_FONT_SIZE = 16;
  static const double H6_FONT_SIZE = 18;
  static const double H5_FONT_SIZE = 21;
  static const double H4_FONT_SIZE = 24;
  static const double H3_FONT_SIZE = 28;
  static const double H2_FONT_SIZE = 31;
  static const double H1_FONT_SIZE = 34;

  static const FontWeight REGULAR_FONT_WEIGHT = FontWeight.w400;
  static const FontWeight MEDIUM_FONT_WEIGHT = FontWeight.w500;
  static const FontWeight DEMI_BOLD_FONT_WEIGHT = FontWeight.w600;
  static const FontWeight BOLD_FONT_WEIGHT = FontWeight.bold;
  static const String APPLICATION_DEFAULT_FONT = 'Graphik';
  static const List<String> APPLICATION_FALLBACK_FONTS = [
    'IranSans',
    'sans-serif'
  ];

  static const Duration SEARCH_INPUT_DEBOUNCE_DURATION =
      Duration(milliseconds: 250);

  static const EdgeInsets PAGE_PADDING = EdgeInsets.symmetric(horizontal: 16);
  static const EdgeInsets CARD_INNER_PADDING =
      EdgeInsets.symmetric(horizontal: 8, vertical: 4);
  static final ShapeBorder CARD_SHAPE =
      RoundedRectangleBorder(borderRadius: BorderRadius.circular(8));
  static const List<List<Color>> AVATAR_GRADIENT_COLORS = [
    [
      Color.fromRGBO(255, 220, 228, 1),
      Color.fromRGBO(251, 187, 202, 1),
      Color.fromRGBO(170, 88, 107, 1)
    ],
    [
      Color.fromRGBO(255, 217, 200, 1),
      Color.fromRGBO(255, 191, 162, 1),
      Color.fromRGBO(158, 103, 77, 1)
    ],
    [
      Color.fromRGBO(255, 229, 168, 1),
      Color.fromRGBO(247, 206, 108, 1),
      Color.fromRGBO(157, 127, 56, 1)
    ],
    [
      Color.fromRGBO(234, 233, 231, 1),
      Color.fromRGBO(213, 212, 211, 1),
      Color.fromRGBO(133, 124, 106, 1)
    ],
    [
      Color.fromRGBO(220, 235, 242, 1),
      Color.fromRGBO(178, 219, 238, 1),
      Color.fromRGBO(76, 125, 148, 1)
    ],
    [
      Color.fromRGBO(202, 223, 242, 1),
      Color.fromRGBO(161, 208, 251, 1),
      Color.fromRGBO(78, 117, 152, 1)
    ],
    [
      Color.fromRGBO(212, 243, 231, 1),
      Color.fromRGBO(173, 233, 209, 1),
      Color.fromRGBO(74, 148, 119, 1)
    ],
    [
      Color.fromRGBO(248, 232, 255, 1),
      Color.fromRGBO(230, 186, 248, 1),
      Color.fromRGBO(138, 85, 161, 1)
    ],
  ];

  static const Map<String, List<String>> emojis = {
    'people': [],
    'activities': [],
    'symbols': [
      ':office:',
      ':bulb:',
      ':briefcase:',
      ':floppy_disk:',
      ':musical_note:',
      ':movie_camera:',
      ':gem:',
      ':hammer_and_pick:',
      ':crossed_swords:',
      ':medical_symbol:',
      ':scales:',
      ':atom_symbol:',
      ':alembic:',
      ':fleur_de_lis:',
      ':warning:',
      ':zap:',
      ':white_circle:',
      ':black_circle:',
      ':coffin:',
      ':funeral_urn:',
      ':soccer:',
      ':baseball:',
      ':snowman_without_snow:',
      ':partly_sunny:',
      ':thunder_cloud_and_rain:',
      ':ophiuchus:',
      ':pick:',
      ':helmet_with_white_cross:',
      ':chains:',
      ':shinto_shrine:',
      ':church:',
      ':mosque:',
      ':latin_cross:',
      ':star_of_david:',
      ':eight_spoked_asterisk:',
      ':eight_pointed_black_star:',
      ':snowflake:',
      ':sparkle:',
      ':x:',
      ':negative_squared_cross_mark:',
      ':heavy_heart_exclamation_mark_ornament:',
      ':curly_loop:',
      ':loop:',
      ':arrow_heading_up:',
      ':arrow_heading_down:',
      ':arrow_left:',
      ':arrow_up:',
      ':arrow_down:',
      ':arrow_right:',
      ':o:',
      ':wavy_dash:',
      ':part_alternation_mark:',
      ':congratulations:',
      ':secret:',
      ':mountain:',
      ':umbrella_on_ground:',
      ':fountain:',
      ':golf:',
      ':ferry:',
      ':boat:',
      ':sailboat:',
      ':skier:',
      ':ice_skate:',
      ':woman-bouncing-ball:',
      ':man-bouncing-ball:',
      ':tent:',
      ':fuelpump:',
      ':scissors:',
      ':airplane:',
      ':email:',
      ':envelope:',
      ':x:',
      ':heavy_multiplication_x:',
      ':heavy_check_mark:',
      ':anchor:',
      ':sagittarius:',
      ':capricorn:',
      ':pisces:',
      ':aquarius:',
      ':white_check_mark:',
      ':warning:',
      ':no_entry_sign:',
      ':no_entry:',
      ':put_litter_in_its_place:',
      ':no_smoking:',
      ':smoking:',
      ':three_button_mouse:',
      ':printer:',
      ':desktop_computer:',
      ':desktop_computer:',
      ':card_index_dividers:',
      ':card_file_box:',
      ':file_cabinet:',
      ':wastebasket:',
      ':spiral_note_pad:',
      ':spiral_calendar_pad:',
      ':compression:',
      ':old_key:',
      ':rolled_up_newspaper:',
      ':dagger_knife:',
      ':speaking_head_in_silhouette:',
      ':left_speech_bubble:',
      ':right_anger_bubble:',
      ':ballot_box_with_ballot:',
      ':world_map:',
      ':black_heart:',
      ':orange_heart:',
      ':heart:',
      ':revolving_hearts:',
      ':heartbeat:',
      ':broken_heart:',
      ':sparkling_heart:',
      ':heartpulse:',
      ':collision:',
      ':bomb:',
      ':boom:',
      ':zzz:',
      ':snowman:',
      ':computer:',
      ':guitar:',
      ':books:',
      ':moneybag:',
      ':speech_balloon:',
      ':thought_balloon:',
      ':white_flower:',
      ':dollar:',
      ':heavy_dollar_sign:',
      ':outbox_tray:',
      ':inbox_tray:',
      ':outbox_tray:',
      ':package:',
      ':e-mail:',
      ':incoming_envelope:',
      ':envelope_with_arrow:',
      ':mailbox_closed:',
      ':mailbox:',
      ':mailbox_with_mail:',
      ':mailbox_with_no_mail:',
      ':postbox:',
      ':postal_horn:',
      ':newspaper:',
      ':iphone:',
      ':no_mobile_phones:',
      ':tv:',
      ':video_game:',
      ':radio:',
      ':film_projector:',
      ':vhs:',
      ':date:',
      ':calendar:',
      ':card_index:',
      ':chart:',
      ':chart_with_upwards_trend:',
      ':chart_with_downwards_trend:',
      ':bar_chart:',
      ':clipboard:',
      ':pushpin:',
      ':round_pushpin:',
      ':paperclip:',
      ':straight_ruler:',
      ':triangular_ruler:',
      ':watch:',
      ':hourglass:',
      ':keyboard:',
      ':eject:',
      ':fast_forward:',
      ':rewind:',
      ':arrow_double_up:',
      ':arrow_double_down:',
      ':closed_lock_with_key:',
      ':prayer_beads:',
      ':twisted_rightwards_arrows:',
      ':repeat:',
      ':repeat_one:',
      ':arrows_clockwise:',
      ':arrows_counterclockwise:',
      ':low_brightness:',
      ':high_brightness:',
      ':mute:',
      ':speaker:',
      ':sound:',
      ':loud_sound:',
      ':battery:',
      ':electric_plug:',
      ':mag:',
      ':mag_right:',
      ':key:',
      ':lock:',
      ':unlock:',
      ':bell:',
      ':no_bell:',
      ':bookmark:',
      ':link:',
      ':radio_button:',
      ':back:',
      ':end:',
      ':on:',
      ':soon:',
      ':underage:',
      ':lock_with_ink_pen:',
      ':100:',
      ':earth_americas:',
      ':dark_sunglasses:',
      ':sun_with_face:',
      ':new_moon_with_face:',
      ':first_quarter_moon_with_face:',
      ':last_quarter_moon_with_face:',
      ':full_moon_with_face:',
      ':star2:',
      ':star:',
      ':fire:',
      ':zap:',
      ':house:',
      ':robot_face:',
      ':alien:',
      ':skull_and_crossbones:',
      ':radioactive_sign:',
      ':biohazard_sign:',
      ':orthodox_cross:',
      ':star_and_crescent:',
      ':peace_symbol:',
      ':yin_yang:',
      ':wheel_of_dharma:',
      ':white_frowning_face:',
      ':relaxed:',
      ':female_sign:',
      ':male_sign:',
      ':gemini:',
      ':cancer:',
      ':leo:',
      ':virgo:',
      ':libra:',
      ':scorpius:',
      ':spades:',
      ':clubs:',
      ':hearts:',
      ':diamonds:',
      ':hotsprings:',
      ':recycle:',
      ':wheelchair:',
      ':skull:',
      ':ribbon:',
      ':family:',
      ':girl:',
      ':boy:',
      ':woman-running:',
      ':man-running:',
      ':gift:',
      ':shopping_trolley:',
      ':bellhop_bell:',
      ':bed:',
      ':place_of_worship:',
      ':octagonal_sign:',
      ':shopping_trolley:',
      ':shield:',
      ':shopping_bags:',
      ':passport_control:',
      ':customs:',
      ':baggage_claim:',
      ':left_luggage:',
      ':couch_and_lamp:',
      ':sleeping_accommodation:',
      ':airplane_departure:',
      ':motor_boat:',
      ':small_airplane:',
      ':airplane_arriving:',
      ':satellite:',
      ':passenger_ship:',
      ':scooter:',
      ':motor_scooter:',
      ':canoe:',
      ':sled:',
      ':baby_symbol:',
      ':shower:',
      ':bath:',
      ':bathtub:',
      ':sports_medal:',
      ':brain:',
      ':billed_cap:',
      ':scarf:',
      ':gloves:',
      ':coat:',
      ':socks:',
      ':bangbang:',
      ':interrobang:',
      ':tm:',
      ':information_source:',
      ':left_right_arrow:',
      ':first_place_medal:',
      ':second_place_medal:',
      ':third_place_medal:',
      ':boxing_glove:',
      ':martial_arts_uniform:',
      ':curling_stone:',
      ':croissant:',
      ':avocado:',
      ':cucumber:',
      ':potato:',
      ':carrot:',
      ':bacon:',
      ':baguette_bread:',
      ':green_salad:',
      ':shallow_pan_of_food:',
      ':stuffed_flatbread:',
      ':egg:',
      ':glass_of_milk:',
      ':peanuts:',
      ':kiwifruit:',
      ':pancakes:',
      ':fortune_cookie:',
      ':takeout_box:',
      ':chopsticks:',
      ':bowl_with_spoon:',
      ':cup_with_straw:',
      ':coconut:',
      ':broccoli:',
      ':dumpling:',
      ':pie:',
      ':pretzel:',
      ':cut_of_meat:',
      ':sandwich:',
      ':exploding_head:',
      ':shocked_face_with_exploding_head:',
      ':pregnant_woman:',
      ':breast-feeding:',
      ':palms_up_together:',
      ':selfie:',
      ':prince:',
      ':princess:',
      ':man_in_tuxedo:',
      ':face_with_symbols_on_mouth:',
      ':serious_face_with_symbols_covering_mouth:',
      ':face_with_hand_over_mouth:',
      ':smiling_face_with_smiling_eyes_and_hand_covering_mouth:',
      ':face_vomiting:',
      ':face_with_open_mouth_vomiting:',
      ':nerd_face:',
      ':face_with_thermometer:',
      ':thinking_face:',
      ':face_with_head_bandage:',
      ':hugging_face:',
      ':joy:',
      ':grin:',
      ':smiley:',
      ':innocent:',
      ':heart_eyes:',
      ':unamused:',
      ':scream:',
      ':expressionless:',
      ':neutral_face:',
      ':pensive:',
      ':sunglasses:',
      ':confused:',
      ':face_with_rolling_eyes:',
      ':stuck_out_tongue:',
      ':worried:',
      ':angry:',
      ':rage:',
      ':cry:',
      ':persevere:',
      ':triumph:',
      ':slightly_frowning_face:',
      ':slightly_smiling_face:',
      ':upside_down_face:',
      ':no_mouth:',
      ':mask:',
      ':zipper_mouth_face:',
      ':money_mouth_face:',
      ':grinning_face_with_star_eyes:',
      ':face_with_cowboy_hat:',
      ':clown_face:',
      ':nauseated_face:',
      ':rolling_on_the_floor_laughing:',
      ':drooling_face:',
      ':lying_face:',
      ':woman-facepalming:',
      ':man-facepalming:',
      ':face_palm:',
      ':sneezing_face:',
      ':face_with_raised_eyebrow:',
      ':face_with_one_eyebrow_raised:',
      ':star-struck:',
      ':grinning_face_with_one_large_and_one_small_eye:',
      ':grinning:',
      ':zany_face:',
      ':shushing_face:',
      ':face_with_finger_covering_closed_lips:',
      ':ok_hand:',
      ':middle_finger:',
      ':raised_hand_with_fingers_splayed:',
      ':spock-hand:',
      ':fist:',
      ':left-facing_fist:',
      ':right-facing_fist:',
      ':sign_of_the_horns:',
      ':call_me_hand:',
      ':raised_back_of_hand:',
      ':handshake:',
      ':crossed_fingers:',
      ':hand_with_index_and_middle_fingers_crossed:',
      ':i_love_you_hand_sign:',
      ':muscle:',
      ':raised_hand:',
      ':black_nib:',
      ':v:',
      ':writing_hand:',
      ':pray:',
      ':ghost:',
      ':crystal_ball:',
      ':dart:',
      ':keycap_ten:',
      ':capital_abcd:',
      ':abcd:',
      ':symbols:',
      ':abc:',
      ':fire:',
      ':flashlight:',
      ':hammer:',
      ':nut_and_bolt:',
      ':hocho:',
      ':knife:',
      ':gun:',
      ':telescope:',
      ':crystal_ball:',
      ':six_pointed_star:',
      ':trident:',
      ':beginner:',
      ':sparkles:',
      ':question:',
      ':grey_question:',
      ':grey_exclamation:',
      ':exclamation:',
      ':heavy_exclamation_mark:',
      ':heavy_plus_sign:',
      ':heavy_minus_sign:',
      ':heavy_division_sign:',
      // ':hash:',
      // ':keycap_star:',
      // ':zero:',
      // ':one:',
      // ':two:',
      // ':three:',
      // ':four:',
      // ':five:',
      // ':six:',
      // ':seven:',
      // ':eight:',
      // ':nine:',
      ':microscope:',
      ':black_square_button:',
      ':white_square_button:',
      ':red_circle:',
      ':large_blue_circle:',
      ':large_orange_diamond:',
      ':large_blue_diamond:',
      ':small_orange_diamond:',
      ':small_blue_diamond:',
      ':small_red_triangle:',
      ':small_red_triangle_down:',
      ':om_symbol:',
      ':dove_of_peace:',
      ':kaaba:',
      ':synagogue:',
      ':menorah_with_nine_branches:',
      ':clock1:',
      ':tulip:',
      ':rainbow:',
      ':bridge_at_night:',
      ':cyclone:',
      ':foggy:',
      ':closed_umbrella:',
      ':night_with_stars:',
      ':stars:',
      ':sunrise_over_mountains:',
      ':sunrise:',
      ':city_sunrise:',
      ':butterfly:',
      ':paw_prints:',
      ':bear:',
      ':deer:',
      ':koala:',
      ':poodle:',
      ':rooster:',
      ':dromedary_camel:',
      ':camel:',
      ':dolphin:',
      ':tiger:',
      ':dragon_face:',
      ':panda_face:',
      ':lion_face:',
      ':fox_face:',
      ':unicorn_face:',
      ':monkey_face:',
      ':zebra_face:',
      ':lion_face:',
      ':giraffe_face:',
      ':zebra_face:',
      ':wolf:',
      ':owl:',
      ':hatched_chick:',
      ':bird:',
      ':penguin:',
      ':pig:',
      ':pig2:',
      ':monkey:',
      ':turtle:',
      ':eagle:',
      ':scorpion:',
      ':turkey:',
      ':duck:',
      ':bat:',
      ':shark:',
      ':gorilla:',
      ':lizard:',
      ':rhinoceros:',
      ':shrimp:',
      ':squid:',
      ':hedgehog:',
      ':sauropod:',
      ':t-rex:',
      ':cricket:',
      ':cheese_wedge:',
      ':face_with_monocle:',
      ':adult:',
      ':child:',
      ':older_adult:',
      ':bearded_person:',
      ':person_with_headscarf:',
      ':woman_in_steamy_room:',
      ':man_in_steamy_room:',
      ':person_in_steamy_room:',
      ':woman_climbing:',
      ':person_climbing:',
      ':man_climbing:',
      ':woman_in_lotus_position:',
      ':person_in_lotus_position:',
      ':man_in_lotus_position:',
      ':female_mage:',
      ':mage:',
      ':male_mage:',
      ':female_fairy:',
      ':fairy:',
      ':female_vampire:',
      ':vampire:',
      ':male_vampire:',
      ':mermaid:',
      ':merman:',
      ':female_elf:',
      ':male_elf:',
      ':female_genie:',
      ':male_genie:',
      ':female_zombie:',
      ':male_zombie:',
      ':zombie:',
      ':smile_cat:',
      ':flying_saucer:',
      ':performing_arts:',
      ':ledger:',
      ':green_book:',
      ':notebook:',
      ':notebook_with_decorative_cover:',
      ':bookmark_tabs:',
      ':mega:',
      ':book:',
      ':closed_book:',
      ':open_book:',
      ':books:',
      ':blue_book:',
      ':orange_book:',
      ':name_badge:',
      ':scroll:',
      ':memo:',
      ':pencil:',
      ':pencil2:',
      ':telephone_receiver:',
      ':pager:',
      ':fax:',
      ':satellite_antenna:',
      ':loudspeaker:',
      ':mega:',
      ':shirt:',
      ':dress:',
      ':ocean:',
      ':volcano:',
      ':milky_way:',
      ':earth_africa:',
      ':earth_americas:',
      ':earth_asia:',
      ':globe_with_meridians:',
      ':new_moon:',
      ':moon:',
      ':droplet:',
      ':sweat_drops:',
      ':dizzy:',
      ':bow:',
      ':see_no_evil:',
      ':hear_no_evil:',
      ':speak_no_evil:',
      ':woman-raising-hand:',
      ':man-raising-hand:',
      ':raising_hand:',
      ':woman-frowning:',
      ':man-frowning:',
      ':person_frowning:',
      ':person_with_pouting_face:',
      ':man-pouting:',
      ':pray:',
      ':construction:',
      ':racing_car:',
      ':ambulance:',
      ':fire_engine:',
      ':police_car:',
      ':taxi:',
      ':oncoming_taxi:',
      ':car:',
      ':red_car:',
      ':oncoming_automobile:',
      ':blue_car:',
      ':bike:',
      ':woman-biking:',
      ':man-biking:',
      ':woman-shrugging:',
      ':man-shrugging:',
      ':shrug:',
      ':woman-cartwheeling:',
      ':man-cartwheeling:',
      ':woman-juggling:',
      ':man-juggling:',
      ':fencer:',
      ':woman-wrestling:',
      ':man-wrestling:',
      ':woman-playing-water-polo:',
      ':man-playing-water-polo:',
      ':woman-playing-handball:',
      ':man-playing-handball:',
      ':bicyclist:',
      ':woman-mountain-biking:',
      ':man-mountain-biking:',
      ':mountain_bicyclist:',
      ':woman-walking:',
      ':man-walking:',
      ':walking:',
      ':wrench:',
      ':rocket:',
      ':helicopter:',
      ':steam_locomotive:',
      ':railway_car:',
      ':bullettrain_side:',
      ':clinking_glasses:',
      ':tumbler_glass:',
      ':spoon:',
      ':drum_with_drumsticks:',
      ':wilted_flower:',
      ':ring:',
      ':crown:',
      ':checkered_flag:',
      ':ship:',
      ':aerial_tramway:',
      ':mountain_cableway:',
      ':suspension_railway:',
      ':mountain_railway:',
      ':monorail:',
      ':tractor:',
      ':woman-rowing-boat:',
      ':man-rowing-boat:',
      ':rowboat:',
      ':speedboat:',
      ':traffic_light:',
      ':vertical_traffic_light:',
      ':construction:',
      ':triangular_flag_on_post:',
      ':door:',
      ':sunrise_over_mountains:',
      ':milky_way:',
      ':tornado:',
      ':tornado_cloud:',
      ':fog:',
      ':wind_blowing_face:',
      ':hotdog:',
      ':burrito:',
      ':taco:',
      ':chestnut:',
      ':evergreen_tree:',
      ':deciduous_tree:',
      ':palm_tree:',
      ':cactus:',
      ':hot_pepper:',
      ':tulip:',
      ':cherry_blossom:',
      ':rose:',
      ':hibiscus:',
      ':sunflower:',
      ':blossom:',
      ':corn:',
      ':ear_of_rice:',
      ':herb:',
      ':four_leaf_clover:',
      ':maple_leaf:',
      ':fallen_leaf:',
      ':leaves:',
      ':mushroom:',
      ':tomato:',
      ':eggplant:',
      ':grapes:',
      ':melon:',
      ':watermelon:',
      ':tangerine:',
      ':lemon:',
      ':banana:',
      ':pineapple:',
      ':apple:',
      ':green_apple:',
      ':peach:',
      ':pear:',
      ':cherries:',
      ':strawberry:',
      ':hamburger:',
      ':pizza:',
      ':meat_on_bone:',
      ':poultry_leg:',
      ':poultry_leg:',
      ':rice_cracker:',
      ':rice_ball:',
      ':rice:',
      ':curry:',
      ':ramen:',
      ':spaghetti:',
      ':bread:',
      ':fries:',
      ':sweet_potato:',
      ':dango:',
      ':oden:',
      ':sushi:',
      ':fried_shrimp:',
      ':fish_cake:',
      ':icecream:',
      ':shaved_ice:',
      ':ice_cream:',
      ':doughnut:',
      ':cookie:',
      ':chocolate_bar:',
      ':candy:',
      ':lollipop:',
      ':custard:',
      ':honey_pot:',
      ':cake:',
      ':bento:',
      ':stew:',
      ':fried_egg:',
      ':cooking:',
      ':fork_and_knife:',
      ':tea:',
      ':sake:',
      ':wine_glass:',
      ':cocktail:',
      ':tropical_drink:',
      ':beer:',
      ':beers:',
      ':baby_bottle:',
      ':knife_fork_plate:',
      ':champagne:',
      ':popcorn:',
      ':birthday:',
      ':christmas_tree:',
      ':jack_o_lantern:',
      ':santa:',
      ':fireworks:',
      ':sparkler:',
      ':tada:',
      ':confetti_ball:',
      ':tanabata_tree:',
      ':crossed_flags:',
      ':flags:',
      ':bamboo:',
      ':rice_scene:',
      ':school_satchel:',
      ':mortar_board:',
      ':medal:',
      ':reminder_ribbon:',
      ':studio_microphone:',
      ':wind_chime:',
      ':level_slider:',
      ':control_knobs:',
      ':film_frames:',
      ':admission_tickets:',
      ':carousel_horse:',
      ':ferris_wheel:',
      ':roller_coaster:',
      ':loop:',
      ':taurus:',
      ':aries:',
      ':1234:',
      ':umbrella_with_rain_drops:',
      ':coffee:',
      ':dancer:',
      ':woman-lifting-weights:',
      ':man-lifting-weights:',
      ':bank:',
      ':money_with_wings:',
      ':yen:',
      ':dollar:',
      ':euro:',
      ':pound:',
      ':left_luggage:',
      ':snowflake:',
      ':spider_web:',
      ':candle:',
      ':mantelpiece_clock:',
      ':hole:',
      ':man_in_business_suit_levitating:',
      ':female-detective:',
      ':male-detective:',
      ':sleuth_or_spy:',
      ':spider:',
      ':joystick:',
      ':man_dancing:',
      ':smile_cat:',
      ':joy_cat:',
      ':smiley_cat:',
      ':heart_eyes_cat:',
      ':kissing_cat:',
      ':pouting_cat:',
      ':crying_cat_face:',
      ':scream_cat:',
      ':alarm_clock:',
      ':timer_clock:',
      ':stopwatch:',
      ':hourglass_flowing_sand:',
      ':double_vertical_bar:',
      ':black_square_for_stop:',
      ':black_circle_for_record:',
      ':m:',
      ':black_small_square:',
      ':white_small_square:',
      ':arrow_forward:',
      ':arrow_backward:',
      ':white_medium_square:',
      ':black_medium_square:',
      ':white_medium_small_square:',
      ':black_medium_small_square:',
      ':sunny:',
      ':cloud:',
      ':umbrella:',
      ':snowman:',
      ':comet:',
      ':phone:',
      ':telephone:',
      ':ballot_box_with_check:',
      ':shamrock:',
      ':point_up:',
    ]
  };
}
